### ISSUE TITLE
Muy bien!!!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m3-evaluacion-intermedia-ayelenperezdemendiola#1]
Buen trabajo @ayelenperezdemendiola  !

Algunas pistas para acabarlo:

- [x] Saca el h1 del componente PokeList, que solo debería tener el listado.
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Limpia e indenta el código
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by ayelenperezdemendiola** [comment]
Hola Carlos! Me podrías dar una pista? porque en la rama "improvements" realicé un ternario para pintar o no pintar una clase, en función de si el nombre del pokemon coincide con el nombre del pokemon seleccionado. No me aparece ni error.... Muchas gracias!!

**Comment by oneeyedman** [comment]
Te ha faltado usar el nombre para el alt de la imagen, por lo demás, muy buen trabajo, Ayelén.
